# -----------------------------------------------------------------
# File: build.yaml
# -----------------------------------------------------------------
include:
  - board: nice_nano
    shield: settings_reset
  - board: nice_nano
    shield: charybdis_left
  - board: nice_nano
    shield: charybdis_right
