# Battery Reporting
CONFIG_ZMK_BATTERY_REPORTING=y

# Pointing (Required for internal driver initialization even if no sensor is attached)
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610=y
